Added a weather command and added the API key to the /token command
rasmuselmgren/sp-bot pull request #41
Opened 2021-08-31 16:30 UTC by rasmuselmgren

2021-08-31 16:42 UTC, stefangeneralao requested changes

2021-08-31 16:42 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +  }
Will catch all errors. Failing API key, network errors and city not found will be caught. The return text will be misleading for some errors

2021-08-31 16:42 UTC, stefangeneralao commented on src/commands/ts/token.ts
> +      `);
This doesn't share the format of the previous message. I suggest not having multiple responses (optional keys) as it forces the user to make multiple copy paste. I suggest exposing all environment variables from one message

2021-08-31 16:42 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +    // If the city is not found, sends an error message. Users cannot user Å, Ä and Ö.
Personally not a fan of comments unless the code is hard to follow. The code is readable, therefore comments are not needed

2021-08-31 16:42 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +      ` and the current weather condition is *${weatherCondition}*`
Why string concat?

2021-08-31 16:42 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +    const weather = await axios.get(
Consider destructuring to `const { data } = await axios.get(`

2021-08-31 16:42 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +const WEATHER_API_KEY = process.env.WEATHER_API_KEY;
Consider destructuring to `const { WEATHER_API_KEY } = process.env;`

2021-08-31 16:45 UTC, rasmuselmgren commented on src/commands/ts/token.ts
> +      `);
My thinking was that the user can chose which keys they want to use rather than getting all of them? Maybe it's better to have it all in one echo command even though some keys might not be used by the user

2021-08-31 16:46 UTC, rasmuselmgren commented on src/commands/ts/weather.ts
> +      ` and the current weather condition is *${weatherCondition}*`
Because I'm not sure how to deal with \n stuff :D

2021-08-31 16:48 UTC, stefangeneralao commented on src/commands/ts/token.ts
> +      `);
This is the way ✊

2021-08-31 16:51 UTC, rasmuselmgren commented on src/commands/ts/weather.ts
> +const WEATHER_API_KEY = process.env.WEATHER_API_KEY;
What's the purpose of this?

2021-08-31 16:54 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +const WEATHER_API_KEY = process.env.WEATHER_API_KEY;
Scalability, readability, tidynessily and other buzzwords.
```
const WEATHER_API_KEY = process.env.WEATHER_API_KEY;
const BANANA_API_KEY = process.env.BANANA_API_KEY;
const APPLE_API_KEY = process.env.APPLE_API_KEY;
const PEAR_API_KEY = process.env.PEAR_API_KEY;
```
VS
```
const {
  WEATHER_API_KEY,
  BANANA_API_KEY,
  APPLE_API_KEY,
  PEAR_API_KEY
} = process.env;
```

2021-08-31 16:56 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +      ` and the current weather condition is *${weatherCondition}*`
Try
```
`The current temperature in *${city}* is: *${temp}* \\u00B0C and the current weather condition is *${weatherCondition}*`
```

2021-09-07 10:19 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +    .replace(/[^a-zA-Z0-9\ ]/g, '');
Hmmmm, smells a bit funky 😄

2021-09-14 05:39 UTC, rasmuselmgren commented on src/commands/ts/weather.ts
> +  mist: ':cloud:',
Ska inte de vara strings? Eller ser jag fel?

2021-09-14 15:23 UTC, stefangeneralao approved these changes

2021-09-14 15:36 UTC, stefangeneralao commented on src/commands/ts/weather.ts
> +  mist: ':cloud:',
Nyckeln behöver inte vara en sträng om det ett ord med vanliga tecken. Med mellanslag eller dylikt behövs citattecken

2021-09-14 15:38 UTC, merged